// Pre-curated high-yield MCQs covering the entire Anti-Cancer Chemotherapy lecture (Slides 1 to 88)
// Available both offline and online without requiring an API Key or Backend Server.

export interface CuratedMCQ {
  id: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  topic: string;
  slideReference: string;
  questionType?: "direct" | "clinical";
}

export const PRE_CURATED_MCQS: CuratedMCQ[] = [
  {
    id: "q_curated_1",
    question: "A 55-year-old male with Acute Lymphoblastic Leukemia is receiving high-dose Methotrexate. Which protective agent must be administered 24 hours after weekly dosing to rescue normal cells from lethal toxicity?",
    options: [
      "Mesna",
      "Folinic acid (Leucovorin)",
      "Dexrazoxane",
      "Allopurinol"
    ],
    correctAnswerIndex: 1,
    explanation: "Leucovorin (folinic acid) provides the active form of reduced folate, bypassing the blocked dihydrofolate reductase (DHFR) enzyme in normal proliferating cells 24 hours after Methotrexate administration.",
    topic: "Antimetabolites - Folic Acid Analogues",
    slideReference: "Slides 21-22",
    questionType: "clinical"
  },
  {
    id: "q_curated_2",
    question: "Before initiating 6-Mercaptopurine (Purinethol®) or Azathioprine, which enzyme screening is clinically mandated to prevent potentially fatal myelosuppression?",
    options: [
      "Dihydropyrimidine Dehydrogenase (DPD)",
      "Thiopurine S-methyltransferase (TPMT)",
      "CYP2D6",
      "Ribonucleotide Reductase"
    ],
    correctAnswerIndex: 1,
    explanation: "TPMT is responsible for the inactivation of 6-mercaptopurine. Patients with genetic deficiency in TPMT accumulate cytotoxic thioguanine nucleotides, leading to severe or fatal bone marrow suppression.",
    topic: "Antimetabolites - Purine Analogues",
    slideReference: "Slide 24",
    questionType: "clinical"
  },
  {
    id: "q_curated_3",
    question: "A patient with Gout is treated with Allopurinol. If this patient subsequently requires 6-Mercaptopurine for Acute Lymphatic Leukemia, what dosage adjustment is required?",
    options: [
      "Increase 6-MP dose by 50%",
      "No dosage adjustment needed",
      "Reduce 6-MP dose by 75% (administer 25% of standard dose)",
      "Double the allopurinol dose"
    ],
    correctAnswerIndex: 2,
    explanation: "Allopurinol inhibits xanthine oxidase, the enzyme that oxidizes 6-MP to inactive thiouric acid. Concurrent therapy leads to dangerously elevated 6-MP levels, so the 6-MP dose must be reduced by 75%.",
    topic: "Antimetabolites - Drug Interactions",
    slideReference: "Slides 24-25",
    questionType: "clinical"
  },
  {
    id: "q_curated_4",
    question: "Which toxic metabolite generated by Cyclophosphamide and Ifosfamide is specifically responsible for inducing hemorrhagic cystitis and bladder fibrosis?",
    options: [
      "Phosphoramide mustard",
      "Chloroacetaldehyde",
      "Acrolein",
      "Semiquinone radical"
    ],
    correctAnswerIndex: 2,
    explanation: "Acrolein is urotoxic and concentrates in the bladder, causing hemorrhagic cystitis and bladder fibrosis. Concomitant Mesna and vigorous hydration neutralize acrolein.",
    topic: "Alkylating Agents - Nitrogen Mustards",
    slideReference: "Slides 36-37",
    questionType: "direct"
  },
  {
    id: "q_curated_5",
    question: "Why is Lomustine (CeeNu®) uniquely prescribed to be taken orally strictly ONCE EVERY 6 WEEKS rather than daily or weekly?",
    options: [
      "It has rapid renal clearance within minutes",
      "It induces severe, delayed, and cumulative myelosuppression",
      "It causes immediate irreversible liver cirrhosis",
      "It permanently blocks gastric absorption"
    ],
    correctAnswerIndex: 1,
    explanation: "Both physician and pharmacist must emphasize to patients that Lomustine is taken only once every 6 weeks because its myelosuppressive nadir is delayed and prolonged; taking it more frequently can cause fatal marrow aplasia.",
    topic: "Alkylating Agents - Nitrosoureas",
    slideReference: "Slide 39",
    questionType: "clinical"
  },
  {
    id: "q_curated_6",
    question: "What is the primary mechanism of action of Doxorubicin ('Red Devil Chemo') that directly underlies its cumulative, dose-dependent, irreversible cardiotoxicity?",
    options: [
      "Inhibition of tubulin depolymerization",
      "Generation of semiquinone and oxygen free radicals that damage cardiomyocytes",
      "Destruction of pancreatic beta cells",
      "Direct degradation of estrogen receptors"
    ],
    correctAnswerIndex: 1,
    explanation: "Anthracyclines generate semiquinone free radicals and hydrogen peroxide / superoxide that overwhelm low antioxidant defenses in cardiac myocytes, resulting in myofibrillar loss and dilated cardiomyopathy.",
    topic: "Cytotoxic Antibiotics - Anthracyclines",
    slideReference: "Slides 49-51",
    questionType: "direct"
  },
  {
    id: "q_curated_7",
    question: "Which FDA Black Box warning applies strictly to Vinca Alkaloids such as Vincristine (Oncovin®)?",
    options: [
      "Fatal if administered intrathecally; IV ONLY",
      "Oral administration must be taken with heavy milk meals",
      "May cause severe hypertension when combined with Leucovorin",
      "Contraindicated in women with ER-positive tumors"
    ],
    correctAnswerIndex: 0,
    explanation: "Vinca alkaloids (Vincristine, Vinblastine, Vinorelbine) are for IV USE ONLY. Accidental intrathecal administration results in ascending encephalopathy and is uniformly fatal.",
    topic: "Microtubule Inhibitors - Vinca Alkaloids",
    slideReference: "Slide 58",
    questionType: "clinical"
  },
  {
    id: "q_curated_8",
    question: "A 48-year-old woman with HER2-positive metastatic breast cancer is receiving Trastuzumab (Herceptin®). Which serious adverse effect requires baseline and routine echocardiography monitoring?",
    options: [
      "Endometrial adenocarcinoma",
      "Heart Failure / Cardiotoxicity (especially if combined with Anthracyclines)",
      "Severe acute interstitial pancreatitis",
      "Idiopathic pulmonary arterial hypertension"
    ],
    correctAnswerIndex: 1,
    explanation: "Trastuzumab targets the extracellular domain of HER2 and can cause cardiotoxicity and heart failure, which is markedly exacerbated when combined with anthracyclines like Doxorubicin.",
    topic: "Monoclonal Antibodies - Trastuzumab",
    slideReference: "Slide 73",
    questionType: "clinical"
  },
  {
    id: "q_curated_9",
    question: "In the American Cancer Society's 7 Warning Signs mnemonic (C.A.U.T.I.O.N.), what does the letter 'U' stand for?",
    options: [
      "Unexplained rapid weight gain",
      "Unusual bleeding or discharge",
      "Ulcerative colitis relapse",
      "Unilateral facial weakness"
    ],
    correctAnswerIndex: 1,
    explanation: "In the classic CAUTION mnemonic: C = Change in bowel/bladder habits; A = A sore that does not heal; U = Unusual bleeding or discharge; T = Thickening or lump; I = Indigestion or difficulty swallowing; O = Obvious change in wart/mole; N = Nagging cough or hoarseness.",
    topic: "Cancer Warning Signs",
    slideReference: "Slide 19",
    questionType: "direct"
  },
  {
    id: "q_curated_10",
    question: "Which chemotherapeutic agent works by inhibiting the BCR-ABL tyrosine kinase generated by the Philadelphia chromosome t(9;22) in Chronic Myelogenous Leukemia (CML)?",
    options: [
      "Erlotinib",
      "Lapatinib",
      "Imatinib (Gleevec®)",
      "Cabazitaxel"
    ],
    correctAnswerIndex: 2,
    explanation: "Imatinib is a prototype tyrosine kinase inhibitor that specifically blocks the ATP-binding pocket of the chimeric BCR-ABL kinase formed by the Philadelphia chromosome in CML and Ph+ ALL.",
    topic: "Tyrosine Kinase Inhibitors",
    slideReference: "Slide 78",
    questionType: "direct"
  },
  {
    id: "q_curated_11",
    question: "Which of the following chemotherapy regimens is specifically used for Hodgkin's Disease and contains Mustine, Oncovin, Procarbazine, and Prednisolone?",
    options: [
      "CHOP",
      "MOPP",
      "FOLFOX",
      "BEP"
    ],
    correctAnswerIndex: 1,
    explanation: "MOPP stands for Mechlorethamine (Mustine) + Oncovin (Vincristine) + Procarbazine + Prednisolone, a classic curative regimen for Hodgkin's disease.",
    topic: "Combination Chemotherapy Regimens",
    slideReference: "Slide 84",
    questionType: "direct"
  },
  {
    id: "q_curated_12",
    question: "Why is Beta-Carotene supplementation strictly contraindicated (must be avoided) in cigarette smokers?",
    options: [
      "It binds to Leucovorin and blocks folic acid synthesis",
      "It significantly INCREASES the risk and incidence of lung cancer in smokers",
      "It causes rapid conversion of ethanol to carcinogenic acetaldehyde",
      "It inhibits cytochrome CYP19A1 aromatase"
    ],
    correctAnswerIndex: 1,
    explanation: "Clinical trials demonstrated that beta-carotene supplementation in smokers actually increases lung cancer rates and mortality; multivitamins containing lutein/beta-carotene (e.g. Centrum lutein) must be avoided in smokers.",
    topic: "Cancer Prevention & Lifestyle",
    slideReference: "Slide 11",
    questionType: "clinical"
  },
  {
    id: "q_curated_13",
    question: "Which chelating cardioprotective agent is co-administered with Doxorubicin to bind intracellular iron and reduce anthracycline-induced dilated cardiomyopathy?",
    options: [
      "Mesna",
      "Dexrazoxane (Zinecard®)",
      "Amifostine",
      "Leucovorin"
    ],
    correctAnswerIndex: 1,
    explanation: "Dexrazoxane is an intracellular iron chelator specifically indicated for preventing or reducing the severity of cardiomyopathy associated with doxorubicin administration in metastatic breast cancer.",
    topic: "Cytotoxic Antibiotics - Protective Agents",
    slideReference: "Slide 51",
    questionType: "direct"
  },
  {
    id: "q_curated_14",
    question: "Taxanes such as Paclitaxel (Taxol®) and Docetaxel (Taxotere®) act upon cancer cells by which distinctive cellular mechanism?",
    options: [
      "Inhibiting tubulin polymerization and preventing mitotic spindle formation",
      "Hyper-stabilizing polymerized microtubules and freezing the cell in M-phase",
      "Intercalating between guanine-cytosine base pairs",
      "Cross-linking DNA strands via alkyl groups at N7 position"
    ],
    correctAnswerIndex: 1,
    explanation: "Unlike Vinca alkaloids which block polymerization, Taxanes promote tubulin assembly and hyper-stabilize microtubules, preventing normal depolymerization and freezing mitosis in metaphase.",
    topic: "Plant Alkaloids - Taxanes",
    slideReference: "Slides 59-60",
    questionType: "direct"
  },
  {
    id: "q_curated_15",
    question: "A 62-year-old postmenopausal woman with ER-positive breast cancer is prescribed Anastrozole (Arimidex®). What is the primary mechanism of action of this drug?",
    options: [
      "Selective Estrogen Receptor Modulator (SERM) in breast tissue",
      "Non-steroidal inhibitor of CYP19A1 Aromatase, preventing androgen-to-estrogen conversion",
      "Recombinant antibody blocking EGFR dimerisation",
      "Inhibition of osteoclastic bone resorption"
    ],
    correctAnswerIndex: 1,
    explanation: "Anastrozole and Letrozole are non-steroidal aromatase inhibitors that block peripheral conversion of androgens to estrogens in postmenopausal women, starving ER-positive tumor cells of estrogen.",
    topic: "Hormone Therapy - Aromatase Inhibitors",
    slideReference: "Slides 65-66",
    questionType: "clinical"
  }
];
